services:
  postgresdb:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
  back:
    build: ./zadatak
    ports:
      - "8081:8081"
    depends_on:
      postgresdb:
        condition: service_healthy
    
volumes:
  data:
