services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'

  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      - backend