services:
  mongodb:
    image: mongo
    volumes:
      - db-data:/data/db
  backend:
    build: ./backend
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - logs:/app/logs
      - ./backend:/app
    ports:
      - "8001:8001"	 
  frontend:
    build: ./frontend
    depends_on:
      - backend 
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  db-data:
  logs:
