services:
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - data:/var/lib/postgresql/data
      
  back:
    build: ./backend
    ports:
      - "9000:8081"
    depends_on:
      pg:
        condition: service_healthy

  front:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - pg
      - back
    stdin_open: true
    tty: true
    
volumes:
  data:
