services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=super
    volumes:
      - ./zadatak/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./public:/public
    depends_on:
      - postgres
      - backend
    stdin_open: true
    tty: true

      
      